### ISSUE TITLE
noise.pt

### ISSUE THREAD

**Issue by Glutaredoxin** [StevenShaw1999/RSSA#1]
hello, Excuse me, where is the noise.pt,  please? load_noise is necessary?

**Comment by StevenShaw1999** [comment]
Hello, sorry that I have forgotten to upload noise.pt and thank you for the reminder!
Accually, load_noise.pt is not necessary in the training phase. But if you want to generate the fixed images in the testing phase, you need to set your 'load_noise' options.

**Comment by StevenShaw1999** [comment]
By the way, I have upload noise.pt just now.

**Comment by Glutaredoxin** [comment]
thank you so so much~
