### ISSUE TITLE
Training (adapting) my own GAN errors

### ISSUE THREAD

**Issue by arith3** [StevenShaw1999/RSSA#3]
Hello.

First of all, thanks for releasing the code. It will be veryvery useful.

I found some issues when training my own images.

[invert_gan.py]
When I want to use a target image more than 5, I have to manually modify range() in line 133.
Can you fix this through the args function?

[train_????_proj.py]
What does the 'assert args.source_key in args.ckpt' in line 775 mean? I delete out the line after make sure it wasn't used.

[model.py]
'latentcode.npy' in the 'exps' directory is used for the existing code, but I checked that the calculated result in 'invert_gan.py' is stored in latent/<mydata>/latent.
So, in 'exp_name' of the init part of 'class Projection_module', I added the code in the same way as latent_dir = 'latent/<mtdata>/latent'. Also, the part that does np.load has been changed appropriately. {np.load(f'%s/{i}_latentcode.npy'%latent_dir)}

I'm training my code like this, and I'm wondering if it's the same as your intended function.
Also, could you please edit the code later?

Thanks.
Have a nice day!

**Comment by StevenShaw1999** [comment]
Hello! Thank you for your reminder!
1 I have modified the code in invert_gan.py. Sorry for that.
2 It's ok to delete this option, it is used in the few-shot-gan-adaption to ensure that you are adapting your model from the right source domains.
3 Thank you for this. I found that I haven't pushed the model.py file to the git after I modified it on the remote server. I have uploaded it just now. You can check it now.

**Comment by arith3** [comment]
Thanks so much for the quick response and update!
