### ISSUE TITLE
Qualitative comparison

### ISSUE THREAD

**Issue by yueanga** [StevenShaw1999/RSSA#5]
Hello！ I wonder how I can  get TGAN results on sketches dataset, as the TGAN does not share the pretrained model of StyleGANv2 on FFHQ.
Thank you so much!!

**Comment by StevenShaw1999** [comment]
Hello, we reproduce the results of TGAN via disabling all of the auxilary losses and training strategies. I suggest you refer to [stylegan2](https://github.com/rosinality/stylegan2-pytorch) to create a pure baseline for TGAN.

**Comment by yueanga** [comment]
okkk！thank you so much!!!
